### ISSUE TITLE
Accès répertoires hors racine Jeedom

### ISSUE THREAD

**Issue by florentin68** [KiboOst/jeedom-jeexplorer#26]
Bonjour,
Serait-il possible de permettre via une option du plugin par exemple que le répertoire racine ne soit pas `/var/www/html` mais plutôt `/` pour avoir accès à tout le système de fichiers ? #

**Comment by KiboOst** [comment]
Bonjour,
Comme déjà dit plusieurs fois sur community, le plugin ne le proposera
- Trop dangereux
- Étant connecté en user et pas en root, vous n'auriez de toute façon pas les droits sur la plupart des fichiers.

çà reste faisable en éditant un fichier ...

**Comment by florentin68** [comment]
Ah ok, je n'avais pas regardé sur le forum effectivement.
Je vais regarder pour la modif fichier.
Ça permettrait au moins d'aller voir `/tmp`.
Merci pour la réponse rapide.

**Comment by florentin68** [comment]
J'ai un peu regarder dans le code mais je ne trouve pas où il faut modifier. Pouvez-vous m'indiquer où cela se trouve ? J'ai cherché `/var/www/html` mais rien trouvé.
