### ISSUE TITLE
Erreur http 403

### ISSUE THREAD

**Issue by DomodomServices** [KiboOst/jeedom-jeexplorer#35]
Bonjour KiboOst.
J'ai une erreur systématiquement à l'ouverture du plugin JeeXplorer depuis la dernière mise à jour  du core de jeedom 4.2 7.
Est-ce une coïncidence ? 
![Screenshot_20220201-213337_Chrome](https://user-images.githubusercontent.com/53484223/152049647-da6b1e6d-268d-4786-af85-066f9f36c37b.jpg)

Merci d'avance. 
Cordialement 
Dominique

**Comment by KiboOst** [comment]
Been long since jeexplorer has been incorporated into Jeedom Core dude ;-)
